### ISSUE TITLE
Estudar DNS

### ISSUE THREAD

**Issue by ghost** [boidacarapreta/arc20211#15]
Obrigatório:

- [x] Estrutura global em árvore
- [x] Domínios
- [x] TLDs e ccTLDs
- [x] Delegação de autoridade
- [x] Registros
- [x] Teste de cliente: registros
- [x] Teste de cliente: recursividade

**Comment by ghost** [comment]
[Primeira aula conceitual](https://youtu.be/FMKwAcDOQeg) publicada no YouTube.

**Comment by beatriz-paz** [comment]
Serviço DNS - 07/07

Vídeo Aula: https://youtu.be/FMKwAcDOQeg

**Comment by ghost** [comment]
[Segunda aula com consultas de registros DNS](https://youtu.be/IQmzZzU6x38) publicado no mesmo canal.
